import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

/** Build-time service worker generator (D5/D6).
 *
 *  Hashed chunk filenames mean any hand-written precache list rots on the
 *  first rebuild, so the precache manifest is computed from the ACTUAL build
 *  outputs: every ./-relative href/src in the built HTML pages plus the
 *  stable shell routes and PWA assets. The cache name is content-hashed, so
 *  a new build atomically swaps the shell cache.
 */

const SHELL_ROUTES = ["/", "/login", "/add", "/settings"];
const PWA_ASSETS = [
  "/manifest.webmanifest",
  "/assets/brand/pwa/icon-192.png",
  "/assets/brand/pwa/icon-512.png",
  "/assets/brand/pwa/apple-touch-icon.png",
];

export async function generateServiceWorker(outDir: string): Promise<void> {
  const assets = new Set<string>();
  for (const page of ["index.html"]) {
    const html = await readFile(join(outDir, page), "utf8");
    for (const match of html.matchAll(/(?:href|src)="(\.\/[^"]+)"/g)) {
      assets.add(match[1].slice(2)); // strip the leading "./"
    }
  }

  const precache = [...SHELL_ROUTES, ...[...assets].sort(), ...PWA_ASSETS];
  const buildId = createHash("sha1").update(precache.join("\n")).digest("hex").slice(0, 12);
  const cacheName = `sugarplum-shell-v${buildId}`;

  const sw = `/* Generated by scripts/generate-sw.ts at build time. Do not edit. */
const CACHE = ${JSON.stringify(cacheName)};
const DATA_CACHE = "sugarplum-data-v1";
const PRECACHE = ${JSON.stringify(precache)};
const SHELL_ROUTES = ${JSON.stringify(SHELL_ROUTES)};
const OFFLINE_JSON = new Response(
  JSON.stringify({ error: "offline" }),
  { status: 503, headers: { "Content-Type": "application/json" } },
);

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE && k !== DATA_CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Writes require connection by design: never queue, surface a JSON 503.
  if (req.method !== "GET") {
    event.respondWith(fetch(req).catch(() => OFFLINE_JSON));
    return;
  }

  const path = url.pathname;

  // App-shell navigations: cache-first (offline reads work). Share links
  // (/share/<token>) serve the cached "/" shell bytes: the token is unknown
  // at build time and token-keyed cache entries would leak it into the cache,
  // while the share DATA (/api/share/*) stays network-only below.
  const isShellRoute = SHELL_ROUTES.includes(path) || path.startsWith("/share/");
  if (req.mode === "navigate" && isShellRoute) {
    const shellKey = SHELL_ROUTES.includes(path) ? path : "/";
    event.respondWith(
      caches
        .match(shellKey)
        .then((cached) => cached || fetch(req).then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(shellKey, copy));
          return res;
        })),
    );
    return;
  }

  // Wishlist reads: stale-while-revalidate; offline serves the last copy.
  const isListRead = path === "/api/wishlist/summary" ||
    (path.startsWith("/api/users/") && path.endsWith("/wishlist"));
  if (isListRead) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(DATA_CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((cached) => cached || OFFLINE_JSON)),
    );
    return;
  }

  // Other /api/* (auth, admin, auth'd image bytes): network only — image
  // bytes must never enter the cache (shared-device privacy).
  if (path.startsWith("/api/")) {
    event.respondWith(fetch(req).catch(() => OFFLINE_JSON));
    return;
  }

  // Static assets (hashed chunks, css): cache-first with populate.
  event.respondWith(
    caches.match(req).then((cached) => cached || fetch(req).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    })),
  );
});
`;

  await writeFile(join(outDir, "sw.js"), sw);
  console.log(`Generated sw.js (cache ${cacheName}, ${precache.length} precache entries)`);
}