/** Every user-facing copy string in the SPA, centralized so a writer pass
 *  edits exactly one file. Components import { S } and never hardcode a
 *  visible literal. Grouped by surface; keys that are not yet used are
 *  allowed to exist (they document the copy surface), literals in JSX are
 *  not. */

export const S = {
  app: {
    name: "sugarplum",
    tagline: "Private wishlists, shared with people you trust.",
    loading: "Loading…",
  },
  auth: {
    signIn: "Sign in",
    signingIn: "Signing in…",
    username: "Username",
    password: "Password",
    signOut: "Log out",
    invalidCredentials: "Invalid username or password.",
    signInFailed: "Sign-in failed.",
    tooManyAttempts: "Too many attempts. Try again later.",
    networkError: "Network error. Try again.",
  },
  list: {
    addItem: "Add item",
    backToMyList: "Back to my list",
    viewList: (name: string) => `View ${name}'s list`,
    heading: (name: string) => `${name}'s wishlist`,
    itemCount: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
  },
  item: {
    edit: "Edit",
    delete: "Delete",
    retry: "Retry fetch",
    retryShort: "Retry",
    fetching: "Fetching details…",
    unavailable: "Details unavailable",
    hintPriceNote: "unverified — via search",
  },
  form: {
    title: "Title",
    price: "Price",
    currency: "Currency",
    currencyCode: "Code",
    link: "Link",
    tags: "Tags",
    notes: "Notes",
    titlePlaceholder: "Leave blank to auto-fill from the link",
    pricePlaceholder: "24.99",
    currencyOther: "Other",
    currencyCodePlaceholder: "SEK",
    linkPlaceholder: "https://…",
    tagsPlaceholder: "Birthday, Someday",
    cancel: "Cancel",
    saving: "Saving…",
    save: "Save",
    needTitleOrLink: "Add a title or a link.",
  },
  claims: {
    claim: "Claim",
    unclaim: "Unclaim",
    claimedByYou: "Claimed by you",
    claimedBySomeone: "Claimed by someone",
  },
  admin: {
    users: "Users",
    name: "Name",
    username: "Username",
    status: "Status",
    actions: "Actions",
    adminRole: "admin",
    userRole: "user",
    inactiveSuffix: " · inactive",
    createUser: "Create user",
    creating: "Creating…",
    deactivate: "Deactivate",
    activate: "Activate",
    resetPassword: "Reset password",
    newPasswordFor: "New password",
    passwordPlaceholder: "New password",
    setPassword: "Set password",
    deleteUserConfirm: (username: string) => `Delete ${username}?`,
    deleteUserBody: "Their items and claims will be removed.",
    passwordReset: "Password reset.",
    userDeleted: "User deleted.",
    delete: "Delete",
    displayName: "Display name",
    password: "Password",
    isAdmin: "Admin",
    createFailed: "Could not create user.",
    requestFailed: "Request failed.",
    networkError: "Network error. Try again.",
  },
  pwa: {
    install: "Install app",
  },
  tags: {
    all: "All",
    filterLabel: "Filter by tag",
  },
  errors: {
    loadWishlist: "Could not load your wishlist. Refresh to try again.",
    retryItem: "Could not retry that item.",
    claimItem: "Could not claim that item.",
    unclaimItem: "Could not unclaim that item.",
    addItem: "Could not add item.",
    saveItem: "Could not save item.",
    deleteItem: "Could not delete item.",
    reorder: "Couldn't save the new order.",
    generic: "Something went wrong. Try again.",
  },
  empty: {
    own: "Nothing saved yet.",
    ownHint: "Paste a product link to start your list.",
    other: (name: string) => `${name} hasn't added anything yet.`,
    filtered: (tag: string) => `No items with tag "${tag}"`,
    clearFilter: "Clear filter",
  },
  dnd: {
    moveItem: "Move item",
  },
  confirm: {
    deleteItem: (title: string) => `Delete "${title}"?`,
    deleteItemBody: "This cannot be undone.",
    cancel: "Cancel",
  },
} as const;