/** Every user-facing copy string in the SPA, centralized so a writer pass
 *  edits exactly one file. Components import { S } and never hardcode a
 *  visible literal. Grouped by surface; keys that are not yet used are
 *  allowed to exist (they document the copy surface), literals in JSX are
 *  not. */

export const S = {
  app: {
    name: "sugarplum",
    tagline: "Private wishlists, shared with people you trust.",
    loading: "Loading…",
  },
  auth: {
    signIn: "Sign in",
    signingIn: "Signing in…",
    username: "Username",
    password: "Password",
    signOut: "Log out",
    invalidCredentials: "Invalid username or password.",
    signInFailed: "Sign-in failed.",
    tooManyAttempts: "Too many attempts. Try again later.",
    networkError: "Network error. Try again.",
  },
  list: {
    addItem: "Add item",
    backToMyList: "Back to my list",
    viewList: (name: string) => `View ${name}'s list`,
    heading: (name: string) => `${name}'s wishlist`,
    itemCount: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
  },
  item: {
    edit: "Edit",
    delete: "Delete",
    retry: "Retry fetch",
    retryShort: "Retry",
    recheckPrice: "Re-check price",
    fetching: "Fetching details…",
    unavailable: "Details unavailable",
    hintPriceNote: "unverified — via search",
    imageViaSearch: "image via search",
    lowestSeen: (price: string) => `Lowest ${price}`,
    atAddPrice: (price: string) => `At add ${price}`,
    downSinceAdd: (amount: string) => `Down ${amount} since added`,
    upSinceAdd: (amount: string) => `Up ${amount} since added`,
    cheaperFound: "Found cheaper:",
    pricesElsewhere: "Prices seen elsewhere (unverified)",
    checkingPrices: "Checking…",
    hintCandidateNote: "check before buying",
    hintsFootnote: "Automated search results. We can't confirm these are the same product or edition.",
    hintsNone: "No other prices found.",
    hintsDisabled: "Price hints are off in settings.",
    copyLink: "Copy link",
    copied: "Copied",
  },
  settings: {
    hintsToggle: "Show unverified price hints",
    on: "On",
    off: "Off",
  },
  form: {
    title: "Title",
    price: "Price",
    currency: "Currency",
    currencyCode: "Code",
    link: "Link",
    cheaperLink: "Found it cheaper at",
    tags: "Tags",
    notes: "Notes",
    titlePlaceholder: "Leave blank to auto-fill from the link",
    pricePlaceholder: "24.99",
    currencyOther: "Other",
    currencyCodePlaceholder: "SEK",
    linkPlaceholder: "https://…",
    cheaperLinkPlaceholder: "https://…",
    tagsPlaceholder: "Birthday, Someday",
    cancel: "Cancel",
    saving: "Saving…",
    save: "Save",
    needTitleOrLink: "Add a title or a link.",
  },
  claims: {
    claim: "Claim",
    unclaim: "Unclaim",
    claimedByYou: "Claimed by you",
    claimedBySomeone: "Claimed by someone",
  },
  share: {
    shareList: "Share my list",
    shareTitle: "Share your wishlist",
    shareIntro:
      "Anyone with this link can view your list and mark items as purchased. Purchased marks are never shown to you.",
    copyLink: "Copy link",
    copied: "Copied",
    createLink: "Create link",
    regenerate: "New link",
    revoke: "Revoke link",
    regenerateConfirmTitle: "Create a new link?",
    regenerateConfirmBody:
      "The current link stops working immediately. Anyone you already sent it to will need the new one.",
    revokeConfirmTitle: "Revoke this link?",
    revokeConfirmBody: "Anyone with the link will no longer be able to view your list.",
    sharedByNote: "Shared list — no account needed",
    markPurchased: "Mark as purchased",
    markPurchasedTitle: "Mark as purchased?",
    markPurchasedBody:
      "This tells other viewers the item is already bought. It will not be shown to the list owner.",
    purchasedBadge: "Purchased",
    invalidLink: "This link is not valid or has been revoked.",
    retryLater: "Too many attempts. Try again later.",
    markFailed: "Could not mark that item.",
    resetPurchased: "Reset purchased mark",
    resetConfirmTitle: "Reset the purchased mark?",
    resetConfirmBody:
      "Purchased marks are anonymous. This clears the mark without telling you who set it.",
    ownerViewingOwn: "You are viewing your own shared list. Purchased marks are hidden from you.",
  },
  admin: {
    users: "Users",
    name: "Name",
    username: "Username",
    status: "Status",
    actions: "Actions",
    adminRole: "admin",
    userRole: "user",
    inactiveSuffix: " · inactive",
    createUser: "Create user",
    creating: "Creating…",
    deactivate: "Deactivate",
    activate: "Activate",
    resetPassword: "Reset password",
    newPasswordFor: "New password",
    passwordPlaceholder: "New password",
    setPassword: "Set password",
    deleteUserConfirm: (username: string) => `Delete ${username}?`,
    deleteUserBody: "Their items and claims will be removed.",
    passwordReset: "Password reset.",
    userDeleted: "User deleted.",
    delete: "Delete",
    displayName: "Display name",
    password: "Password",
    isAdmin: "Admin",
    createFailed: "Could not create user.",
    requestFailed: "Request failed.",
    networkError: "Network error. Try again.",
  },
  pwa: {
    install: "Install app",
  },
  tags: {
    all: "All",
    filterLabel: "Filter by tag",
  },
  errors: {
    loadWishlist: "Could not load your wishlist. Refresh to try again.",
    retryItem: "Could not retry that item.",
    checkPrices: "Could not check prices.",
    changeSettings: "Could not save that setting.",
    claimItem: "Could not claim that item.",
    unclaimItem: "Could not unclaim that item.",
    addItem: "Could not add item.",
    saveItem: "Could not save item.",
    deleteItem: "Could not delete item.",
    reorder: "Couldn't save the new order.",
    generic: "Something went wrong. Try again.",
  },
  empty: {
    own: "Nothing saved yet.",
    ownHint: "Paste a product link to start your list.",
    other: (name: string) => `${name} hasn't added anything yet.`,
    filtered: (tag: string) => `No items with tag "${tag}"`,
    clearFilter: "Clear filter",
  },
  dnd: {
    moveItem: "Move item",
  },
  confirm: {
    deleteItem: (title: string) => `Delete "${title}"?`,
    deleteItemBody: "This cannot be undone.",
    cancel: "Cancel",
  },
} as const;